version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: gin_app
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: gin_mysql
    restart: always
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    container_name: gin_redis
    tty: true
    ports:
      - 6379:6379
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gin_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=$PMA_USER
      - PMA_PASSWORD=$PMA_PASSWORD
    links:
      - db
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
